# render.yaml
services:
  - type: web
    name: paytm-mcp
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn paytm_mcp:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PAYTM_MID
        value: ""  # Set this in Render dashboard
      - key: PAYTM_KEY_SECRET
        value: ""  # Set this in Render dashboard

